version: "3.9"

services:
  frontend:
    build: ./fitness-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./fitness-tracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: 60000
      SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT: 30000
      SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: 5000
      SPRING_DATASOURCE_INITIALIZATION_MODE: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitdb
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
